# Generated by Django 3.0 on 2020-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userfeedback_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='empty',
            field=models.BooleanField(default=False),
        ),
    ]
