# Generated by Django 3.0 on 2020-01-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_url_empty'),
    ]

    operations = [
    ]
